---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno
  - volsync/ks.yaml
  - system-upgrade-controller/ks.yaml
  - node-feature-discovery/ks.yaml
  - spegel
  - tuppr
